### ISSUE TITLE
[🔄 Refactor] 로그인, 회원가입시 기존 커스텀인증 파이어베이스 Auth로 리팩토링

### ISSUE THREAD

**Issue by whwjdan** [Dev-FE-2/toy-project2-team1#24]
### 📄 설명

- 로그인, 회원가입시 기존 커스텀인증 파이어베이스 Auth로 리팩토링

### 📋 체크리스트

- [ ] 로그인, 회원가입시 기존 커스텀인증 파이어베이스 Auth로 리팩토링

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

This change refactors the login and registration process to use Firebase Auth instead of the custom authentication. It updates the firebaseConfig, useFirebaseAuth hook, Login component, and Register component to work with Firebase Auth.

You can review changes in this commit: https://github.com/lkilu6456546/Dev-FE-2-toy-project2-team1-24/commit/c8cc60ad4d1e1c971fbf9ef249fe723c3f2868ab.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
